FROM node:19-alpine 

# COPY package.json /app/ 
# COPY package-lock.json /app/
# COPY vite.config.ts /app/
# COPY tsconfig.json /app/
# COPY tsconfig.node.json /app/
# COPY index.html /app/
# COPY .eslintrc.cjs /app/
# COPY .gitignore /app/
# COPY src /app/

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install 

COPY . .

EXPOSE 5173


CMD ["npm", "run", "dev"]
# CMD ["node", "server.js"]

